### ISSUE TITLE
Crashes on NFT with name as empty string

### ISSUE THREAD

**Issue by neilshah2000** [minima-global/Wallet#26]
TokenListItem.tsx

````
<Typography noWrap={true} variant="body2">
    {item.token.name ? item.token.name : 'item.token'}
</Typography>
````

This line causes the wallet app to crash if its an nft type token but name is empty string ''

Wallet ui doesnt actually allow an nft with no name, but nft app does (will fix the nft app for that)

**Comment by eliasnemr** [comment]
Fixed by applying this check,

`item.token && typeof item.token === 'object' && item.token.hasOwnProperty('name')
                            ? item.token.name
                            : item.token && typeof item.token === 'string'
                            ? item.token
                            : 'Invalid name'`

**Comment by eliasnemr** [comment]
Added NFT/Token interface checks to ensure correct type, otherwise unsupported response when clicking for details in v1.10
